/******************************************************************************
 *                                  LICENSE                                   *
 ******************************************************************************
 *  This file is free software: you can redistribute it and/or modify         *
 *  it under the terms of the GNU General Public License as published by      *
 *  the Free Software Foundation, either version 3 of the License, or         *
 *  (at your option) any later version.                                       *
 *                                                                            *
 *  This file is distributed in the hope that it will be useful,              *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 *  GNU General Public License for more details.                              *
 *                                                                            *
 *  You should have received a copy of the GNU General Public License         *
 *  along with this file.  If not, see <https://www.gnu.org/licenses/>.       *
 ******************************************************************************
 *  Purpose:                                                                  *
 *      Creates aliases for the functions generated by emscripten. The C      *
 *      for a function is function_name and emscripten prepends an underscore *
 *      producing _function_name. This file allows the function to be called  *
 *      in JavaScript by typing functionName, as is most common.              *
 ******************************************************************************
 *  Author:     Ryan Maguire                                                  *
 *  Date:       October 30, 2025                                              *
 ******************************************************************************/
createModule.generateIndices = createModule._generate_indices;
createModule.generateMesh = createModule._generate_mesh;
createModule.getIndexBuffer = createModule._get_index_buffer;
createModule.getMeshBuffer = createModule._get_mesh_buffer;
createModule.rotateMesh = createModule._rotate_mesh;
createModule.setRotationAngle = createModule._set_rotation_angle;
