/******************************************************************************
 *                                  LICENSE                                   *
 ******************************************************************************
 *  This file is free software: you can redistribute it and/or modify         *
 *  it under the terms of the GNU General Public License as published by      *
 *  the Free Software Foundation, either version 3 of the License, or         *
 *  (at your option) any later version.                                       *
 *                                                                            *
 *  This file is distributed in the hope that it will be useful,              *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 *  GNU General Public License for more details.                              *
 *                                                                            *
 *  You should have received a copy of the GNU General Public License         *
 *  along with this file.  If not, see <https://www.gnu.org/licenses/>.       *
 ******************************************************************************
 *  Purpose:                                                                  *
 *      Creates aliases for the functions generated by emscripten. The C      *
 *      for a function is function_name and emscripten prepends an underscore *
 *      producing _function_name. This file allows the function to be called  *
 *      in JavaScript by typing functionName, as is most common.              *
 ******************************************************************************
 *  Author:     Ryan Maguire                                                  *
 *  Date:       October 30, 2025                                              *
 ******************************************************************************/
import initModule from "../main.js";

const module = await initModule();

export const generateIndices = module._generate_indices;
export const generateMesh = module._generate_mesh;
export const indexBufferAddress = module._get_index_buffer;
export const meshBufferAddress = module._get_mesh_buffer;
export const rotateMesh = module._rotate_mesh;
export const setRotationAngle = module._set_rotation_angle;
export const memory = module.HEAP8;

export function setupMesh(parameters) {
    const numberOfPoints = parameters.nxPts * parameters.nyPts;
    const sum = parameters.nxPts + parameters.nyPts;
    const bufferSize = 3 * numberOfPoints;
    const indexSize = 2 * (2 * numberOfPoints - sum);

    const meshPtr = meshBufferAddress();
    const indexPtr = indexBufferAddress();

    const mesh = new Float32Array(memory.buffer, meshPtr, bufferSize);
    const indices = new Uint32Array(memory.buffer, indexPtr, indexSize);

    generateMesh(mesh.byteOffset, parameters.nxPts, parameters.nyPts);
    generateIndices(indices.byteOffset, parameters.nxPts, parameters.nyPts);
}

async function createModule() {
    const Module = {
        generateIndices,
        generateMesh,
        rotateMesh,
        meshBufferAddress,
        indexBufferAddress,
        setRotationAngle,
        memory,
        setupMesh
    };

    return Module;
}

export default createModule;
