################################################################################
#                                   LICENSE                                    #
################################################################################
#   This file is part of threejs_figures.                                      #
#                                                                              #
#   threejs_figures is free software: you can redistribute it and/or modify    #
#   it under the terms of the GNU General Public License as published by       #
#   the Free Software Foundation, either version 3 of the License, or          #
#   (at your option) any later version.                                        #
#                                                                              #
#   threejs_figures is distributed in the hope that it will be useful,         #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#   GNU General Public License for more details.                               #
#                                                                              #
#   You should have received a copy of the GNU General Public License          #
#   along with threejs_figures.  If not, see <https://www.gnu.org/licenses/>.  #
################################################################################
#   Author:     Ryan Maguire                                                   #
#   Date:       March 25, 2026                                                 #
################################################################################

.PHONY: all clean

all:
	npm install .
	npm run build

clean:
	rm -rf node_modules
	rm -rf dist
	rm -f package-lock.json
