/******************************************************************************
 *                                  LICENSE                                   *
 ******************************************************************************
 *  This file is free software: you can redistribute it and/or modify         *
 *  it under the terms of the GNU General Public License as published by      *
 *  the Free Software Foundation, either version 3 of the License, or         *
 *  (at your option) any later version.                                       *
 *                                                                            *
 *  This file is distributed in the hope that it will be useful,              *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 *  GNU General Public License for more details.                              *
 *                                                                            *
 *  You should have received a copy of the GNU General Public License         *
 *  along with this file.  If not, see <https://www.gnu.org/licenses/>.       *
 ******************************************************************************
 *  Purpose:                                                                  *
 *      Creates aliases for the functions generated by emscripten. The C      *
 *      for a function is function_name and emscripten prepends an underscore *
 *      producing _function_name. This file allows the function to be called  *
 *      in JavaScript by typing functionName, as is most common.              *
 ******************************************************************************
 *  Author:     Ryan Maguire                                                  *
 *  Date:       October 30, 2025                                              *
 ******************************************************************************/
import initModule from "main";

/*  emscripten compiles everything into a module. Initialize it.              */
const module = await initModule();

/*  Export the C functions so that may be called in JavaScript.               */
export const indexBufferAddress = module.indexBufferAddress;
export const mainCanvasAddress = module.mainCanvasAddress;
export const meshBufferAddress = module.meshBufferAddress;
export const memory = module.HEAP8;
export const setupMesh = module.setupMesh;
export const setRotationAngle = module.setRotationAngle;
export const zRotateCanvas = module.zRotateCanvas;
