/******************************************************************************
 *                                  LICENSE                                   *
 ******************************************************************************
 *  This file is free software: you can redistribute it and/or modify         *
 *  it under the terms of the GNU General Public License as published by      *
 *  the Free Software Foundation, either version 3 of the License, or         *
 *  (at your option) any later version.                                       *
 *                                                                            *
 *  This file is distributed in the hope that it will be useful,              *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 *  GNU General Public License for more details.                              *
 *                                                                            *
 *  You should have received a copy of the GNU General Public License         *
 *  along with this file.  If not, see <https://www.gnu.org/licenses/>.       *
 ******************************************************************************
 *  Purpose:                                                                  *
 *      Creates aliases for the functions generated by emscripten. The C      *
 *      for a function is function_name and emscripten prepends an underscore *
 *      producing _function_name. This file allows the function to be called  *
 *      in JavaScript by typing functionName, as is most common.              *
 ******************************************************************************
 *  Author:     Ryan Maguire                                                  *
 *  Date:       October 30, 2025                                              *
 ******************************************************************************/
import initModule from "main";

const module = await initModule();

export default async function createModule() {
    return {
        indexBufferAddress: module._index_buffer_address,
        mainCanvasAddress: module._main_canvas_address,
        meshBufferAddress: module._mesh_buffer_address,
        rotateMainCanvas: module._rotate_main_canvas,
        setRotationAngle: module._set_rotation_angle,
        memory: module.HEAP8,
        setupMesh: module.setupMesh
    };
}
