/******************************************************************************
 *                                  LICENSE                                   *
 ******************************************************************************
 *  This file is free software: you can redistribute it and/or modify         *
 *  it under the terms of the GNU General Public License as published by      *
 *  the Free Software Foundation, either version 3 of the License, or         *
 *  (at your option) any later version.                                       *
 *                                                                            *
 *  This file is distributed in the hope that it will be useful,              *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 *  GNU General Public License for more details.                              *
 *                                                                            *
 *  You should have received a copy of the GNU General Public License         *
 *  along with this file.  If not, see <https://www.gnu.org/licenses/>.       *
 ******************************************************************************
 *  Purpose:                                                                  *
 *      Creates aliases for the functions generated by emscripten.            *
 ******************************************************************************
 *  Author:     Ryan Maguire                                                  *
 *  Date:       October 30, 2025                                              *
 ******************************************************************************/

/*  Stats allows the frame rate to be shown while the animation runs.         */
import {Stats} from "three";

/*  emscripten compiles everything into an ES6 module. Initialize it.         */
const module = await initModule();

/*  Export the C functions so that may be called in JavaScript.               */
export const basicWireframe = module.basicWireframe;
export const canvasObjectAddress = module.canvasObjectAddress;
export const indexBufferAddress = module.indexBufferAddress;
export const initGeometry = module.initGeometry;
export const mainCanvasAddress = module.mainCanvasAddress;
export const meshBufferAddress = module.meshBufferAddress;
export const memory = module.HEAP8;
export const sceneCamera = module.sceneCamera;
export const sceneFromSurface = module.sceneFromSurface;
export const sceneRenderer = module.sceneRenderer;
export const setupControls = module.setupControls;
export const setupMesh = module.setupMesh;
export const setRotationAngle = module.setRotationAngle;
export const squareWireframeGeometry = module.squareWireframeGeometry;
export const windowResize = module.windowResize;
export const zRotateCanvas = module.zRotateCanvas;
export const zRotate = module.zRotate;
export {Stats};
